volunteer-community/volunteer-backend

src/main/java/com/maple/volunteer/controller/user/UserController.java, src/main/java/com/maple/volunteer/domain/user/User.java, src/main/java/com/maple/volunteer/dto/user/SignupDto.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/security/SecurityConfig.java, src/main/java/com/maple/volunteer/security/oauth2/MyAuthenticationSuccessHandler.java, src/main/java/com/maple/volunteer/service/user/UserService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java, src/main/java/com/maple/volunteer/type/SuccessCode.java, src/main/resources/application-aws.yml, src/main/resources/application-db.yml, src/main/resources/application-jwt.yml, src/main/resources/application-oauth.yml, src/main/resources/application.yml
=> signup pullrequest

src/main/java/com/maple/volunteer/controller/poster/PosterController.java, src/main/java/com/maple/volunteer/domain/poster/Poster.java, src/main/java/com/maple/volunteer/dto/poster/PosterDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterRequestDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterUpdateDto.java, src/main/java/com/maple/volunteer/repository/communityuser/CommunityUserRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/repository/posterimg/PosterImgRepository.java, src/main/java/com/maple/volunteer/service/poster/PosterService.java, src/main/java/com/maple/volunteer/service/s3upload/S3UploadService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java, src/main/java/com/maple/volunteer/type/SuccessCode.java
=> poster update, create

src/main/java/com/maple/volunteer/controller/comment/CommentController.java, src/main/java/com/maple/volunteer/controller/community/CommunityController.java, src/main/java/com/maple/volunteer/controller/example/ExampleController.java, src/main/java/com/maple/volunteer/controller/heart/HeartController.java, src/main/java/com/maple/volunteer/controller/poster/PosterController.java, src/main/java/com/maple/volunteer/domain/heart/Heart.java, src/main/java/com/maple/volunteer/domain/poster/Poster.java, src/main/java/com/maple/volunteer/domain/user/User.java, src/main/java/com/maple/volunteer/dto/comment/CommentListResponseDto.java, src/main/java/com/maple/volunteer/dto/comment/CommentResponseDto.java, src/main/java/com/maple/volunteer/dto/heart/HeartRequestDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterDetailListResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterDetailResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterImgResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterListResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterResponseDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/communityuser/CommunityUserRepository.java, src/main/java/com/maple/volunteer/repository/heart/HeartRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/security/config/security2/SecurityConfig.java, src/main/java/com/maple/volunteer/service/comment/CommentService.java, src/main/java/com/maple/volunteer/service/heart/HeartService.java, src/main/java/com/maple/volunteer/service/poster/PosterService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java, src/main/java/com/maple/volunteer/type/SuccessCode.java
=> poster , heart add function 

src/main/java/com/maple/volunteer/controller/user/UserController.java, src/main/java/com/maple/volunteer/dto/user/CheckDto.java, src/main/java/com/maple/volunteer/dto/user/SignupDto.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/service/user/UserService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java, src/main/java/com/maple/volunteer/type/SuccessCode.java
=> user check pull request

src/main/java/com/maple/volunteer/dto/user/SignupDto.java, src/main/java/com/maple/volunteer/service/user/UserService.java
=> user signup refreshToken save pull request

src/main/java/com/maple/volunteer/controller/comment/CommentController.java, src/main/java/com/maple/volunteer/controller/heart/HeartController.java, src/main/java/com/maple/volunteer/dto/comment/CommentRequestDto.java, src/main/java/com/maple/volunteer/dto/heart/HeartRequestDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/communityuser/CommunityUserRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/service/comment/CommentService.java, src/main/java/com/maple/volunteer/service/community/CommunityService.java, src/main/java/com/maple/volunteer/service/heart/HeartService.java, src/main/java/com/maple/volunteer/service/poster/PosterService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java, src/main/java/com/maple/volunteer/type/SuccessCode.java
Connect users to like and comment functions
=> connect users to like and comment functions

src/main/java/com/maple/volunteer/controller/poster/PosterController.java, src/main/java/com/maple/volunteer/dto/comment/CommentResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterDetailResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterResponseDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/service/comment/CommentService.java, src/main/java/com/maple/volunteer/service/poster/PosterService.java
댓글과 게시글 조회할때 사용자 프로필이미지 반환 추가했습니다.
=> add profileImg to poster & comment

src/main/java/com/maple/volunteer/controller/mypage/MyPageController.java, src/main/java/com/maple/volunteer/domain/common/BaseTime.java, src/main/java/com/maple/volunteer/dto/comment/CommentResponseDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/heart/HeartRepository.java, src/main/java/com/maple/volunteer/security/config/dateFormat/DateFormatConfiguration.java, src/main/java/com/maple/volunteer/service/mypage/MyPageService.java, src/main/resources/application.yml
=> add DateFormat Type

src/main/java/com/maple/volunteer/controller/user/UserController.java, src/main/java/com/maple/volunteer/dto/user/NewUserDto.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/service/user/UserService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java
=> user errorcode pull request

src/main/java/com/maple/volunteer/controller/user/UserController.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/service/user/UserService.java
=> signup add provider pull request

src/main/java/com/maple/volunteer/controller/user/UserController.java, src/main/java/com/maple/volunteer/domain/login/Login.java, src/main/java/com/maple/volunteer/domain/user/User.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/security/oauth2/CustomOAuth2UserService.java, src/main/java/com/maple/volunteer/security/oauth2/MyAuthenticationSuccessHandler.java, src/main/java/com/maple/volunteer/security/oauth2/OAuth2Attribute.java, src/main/java/com/maple/volunteer/service/user/UserService.java, src/main/resources/application-oauth.yml
=> Configurate Kakao Login

src/main/java/com/maple/volunteer/controller/admin/AdminController.java, src/main/java/com/maple/volunteer/dto/user/TokenDto.java, src/main/java/com/maple/volunteer/dto/user/UserDto.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/security/jwt/dto/GeneratedToken.java, src/main/java/com/maple/volunteer/security/jwt/service/JwtUtil.java, src/main/java/com/maple/volunteer/service/user/UserService.java
- Add refreshTokenExpireTime at TokenDto
- Add user inquiry by nickname
=> User features changed

src/main/java/com/maple/volunteer/controller/mypage/MyPageController.java, src/main/java/com/maple/volunteer/domain/user/User.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/community/CommunityRepository.java, src/main/java/com/maple/volunteer/repository/communityuser/CommunityUserRepository.java, src/main/java/com/maple/volunteer/repository/heart/HeartRepository.java, src/main/java/com/maple/volunteer/repository/login/LoginRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/repository/posterimg/PosterImgRepository.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/service/community/CommunityService.java, src/main/java/com/maple/volunteer/service/mypage/MyPageService.java, src/main/java/com/maple/volunteer/service/user/UserService.java, src/main/java/com/maple/volunteer/type/SuccessCode.java
=> User Withdrawal

src/main/java/com/maple/volunteer/domain/poster/Poster.java, src/main/java/com/maple/volunteer/dto/community/CommunityDetailAndImgResponseDto.java, src/main/java/com/maple/volunteer/dto/community/CommunityUserDetailDto.java, src/main/java/com/maple/volunteer/dto/poster/CommentUserResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/CommunityHostResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterDetailListResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterListResponseDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/community/CommunityRepository.java, src/main/java/com/maple/volunteer/repository/communityuser/CommunityUserRepository.java, src/main/java/com/maple/volunteer/repository/heart/HeartRepository.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/service/community/CommunityService.java, src/main/java/com/maple/volunteer/service/mypage/MyPageService.java, src/main/java/com/maple/volunteer/service/poster/PosterService.java
Improve community, poster function
=> Improve community, poster function 

src/main/java/com/maple/volunteer/controller/admin/AdminController.java, src/main/java/com/maple/volunteer/service/admin/AdminService.java, src/main/java/com/maple/volunteer/service/user/UserService.java
=> Change folder

src/main/java/com/maple/volunteer/controller/mypage/MyPageController.java, src/main/java/com/maple/volunteer/controller/user/UserController.java, src/main/java/com/maple/volunteer/dto/mypage/MyPageResponseDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/community/CommunityRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/service/mypage/MyPageService.java, src/main/java/com/maple/volunteer/service/user/UserService.java, src/main/java/com/maple/volunteer/type/ErrorCode.java
=> userinfo pr

src/main/java/com/maple/volunteer/controller/community/CommunityController.java, src/main/java/com/maple/volunteer/domain/category/Category.java, src/main/java/com/maple/volunteer/domain/comment/Comment.java, src/main/java/com/maple/volunteer/domain/community/Community.java, src/main/java/com/maple/volunteer/domain/communityimg/CommunityImg.java, src/main/java/com/maple/volunteer/domain/communityuser/CommunityUser.java, src/main/java/com/maple/volunteer/domain/heart/Heart.java, src/main/java/com/maple/volunteer/domain/poster/Poster.java, src/main/java/com/maple/volunteer/domain/posterimg/PosterImg.java, src/main/java/com/maple/volunteer/domain/user/User.java, src/main/java/com/maple/volunteer/dto/community/CommunityRequestDto.java, src/main/java/com/maple/volunteer/service/community/CommunityService.java, src/main/resources/application.yml
=> dev to main pr

src/main/java/com/maple/volunteer/domain/poster/Poster.java, src/main/java/com/maple/volunteer/dto/mypage/MyPageResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterDetailResponseDto.java, src/main/java/com/maple/volunteer/dto/poster/PosterResponseDto.java, src/main/java/com/maple/volunteer/repository/comment/CommentRepository.java, src/main/java/com/maple/volunteer/repository/heart/HeartRepository.java, src/main/java/com/maple/volunteer/repository/poster/PosterRepository.java, src/main/java/com/maple/volunteer/service/comment/CommentService.java, src/main/java/com/maple/volunteer/service/community/CommunityService.java, src/main/java/com/maple/volunteer/service/mypage/MyPageService.java, src/main/java/com/maple/volunteer/service/poster/PosterService.java
=> Edit post, my page logic

src/main/java/com/maple/volunteer/controller/mypage/MyPageController.java, src/main/java/com/maple/volunteer/repository/user/UserRepository.java, src/main/java/com/maple/volunteer/security/oauth2/MyAuthenticationSuccessHandler.java, src/main/java/com/maple/volunteer/service/mypage/MyPageService.java, src/main/java/com/maple/volunteer/type/Role.java, src/main/java/com/maple/volunteer/type/SuccessCode.java
=> Mypage Rankup

src/main/java/com/maple/volunteer/controller/admin/AdminController.java, src/main/java/com/maple/volunteer/controller/community/CommunityController.java, src/main/java/com/maple/volunteer/security/config/MethodSecurityConfig.java, src/main/java/com/maple/volunteer/security/config/SecurityConfig.java, src/main/java/com/maple/volunteer/security/jwt/config/JwtAuthFilter.java, src/main/java/com/maple/volunteer/security/jwt/dto/SecurityUserDto.java, src/main/java/com/maple/volunteer/service/user/UserService.java
=> Configure Authorization
